### ISSUE TITLE
customer churn predictor : kafka install

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hazelcast-jet-demos#17]
Would be better if we give instructions and have the demo work with a docker image for kafka rather than making people download it onto their systems.

**Comment by dbrimley** [comment]
We should actually extend the kafka image with our own so we can add the topics cutting out a step for the user.

**Comment by rimogitz** [comment]
JetChurnPredictor  is now refactored to launch without kafka. The module now loads the necessary contract data direct from file along with PMML model. The input is a list of Mobile phone numbers which is passed to Jet to execute as batch and predict the propensity to churn using the Pmml model.
This is done to get a working demo which is easy to run  in readiness to webinar and also fits the brief from Vlad.
I will look into getting it work with Kafka docker  once I get time after webinar
