### ISSUE TITLE
customer churn predictor : README

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hazelcast-jet-demos#18]
I have no idea what this application does, we need a few paragraphs explaining the use case.

**Comment by dbrimley** [comment]
So we need two sections, 1-3 paragraphs that clearly outline the use case and then another section that describes how using Hazelcast Jet solves this use case, with links to code snippets etc.  We need to convey how Jet is a good solution.

**Comment by rimogitz** [comment]
Please see the updated  project JetChurnPredictor .  Jet uses a custom processor to take a batch of phone numbers and analyse the contracts for churn using PMML model  loaded in embedded JPMML Engine.
