### ISSUE TITLE
Clean Code : flight-telemetry

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hazelcast-jet-demos#33]
https://github.com/hazelcast/hazelcast-jet-demos/blob/master/flight-telemetry/src/main/java/com/hazelcast/jet/demo/Demo.java

As a Java engineer new to Jet I would look at this class and wonder what the hell is going on.

Can we please break down the build of the DAG into atomic methods that are cleanly described and have instructive JavaDocs.  So for example when you build Noise Levels have that in its own method.

Right now we have one long method that is very scarey to read.

**Comment by eminn** [comment]
Added the text visualization of the DAG for now https://github.com/hazelcast/hazelcast-jet-demos/blob/master/flight-telemetry/src/main/java/com/hazelcast/jet/demo/FlightTelemetry.java#L61
