### ISSUE TITLE
Please do not override the ADSBx checks for the data stream.

### ISSUE THREAD

**Issue by adsbxchange** [hazelcast/hazelcast-jet-demos#77]
Please see https://adsbexchange.com/data/ 

You endangering ADSBx project and infrastructure by forcibly working around the protections in place.

This is unacceptable.

ADSBX

**Comment by cangencer** [comment]
Hi @adsbxchange, 

This is a demo application (non-commercial) to show capabilities of Hazelcast Jet which is a streaming framework. It's not meant to be running all the time and just used a code sample to showcase various features of Hazelcast Jet. 

At the time it was developed the URL we are using was what was documented on your page - please see from https://web.archive.org/web/20180402131001/https://adsbexchange.com/data/#:

> Querying Live Position Data
> 
> Live position data can be queried with various parameters are results returned in a JSON format. As you may be aware, ADSBexchange is based on the excellent Virtual Radar Server product by Andrew Whewell.
> 
> Full documentation on the query format, and the query response is available here.
> 
> The base URL to query is: http://public-api.adsbexchange.com/VirtualRadar/AircraftList.json (querying this URL by itself will yield a JSON with _all_ airborne aircraft).

We are not forcibly working around any protections but just using what was the documented API at the time.

It looks like since you've changed your API and how it's accessed,  we were not aware of this. Please advise us on the best way to access the data going forward for the purpose I described above.

**Comment by adsbxchange** [comment]
That end point will be deprecated due to abuse by commercial institutions and users.

All Enthusiast non-commercial access requires hosting of a reliable ADS-B feeder sending data to ADSBx.

Enthusiast feeders then request an API key from ADSBx.  To get data, they send a header a called api-auth with the value of key with each request.

Such as:

curl -H "api-auth:<insert key>" https://adsbexchange.com/api/aircraft/all/

More end points are located at: https://www.adsbexchange.com/data/

{
	"ac": [{
		"postime": "1554216728906",
		"icao": "800B4B",
		"reg": "",
		"type": "",
		"spd": "158.3",
		"alt": "1500",
		"lat": "28.544724",
		"lon": "77.07617",
		"vsi": "2688",
		"trak": "281.7",
		"sqk": "",
		"call": "",
		"gnd": "0",
		"trt": "2",
		"pos": "1",
		"mlat": "0",
		"tisb": "0",
		"mil": "0"
	}, {
		"postime": "1554216728905",
		"icao": "7804AD",
		"reg": "",
		"type": "",
		"spd": "370",
		"alt": "21600",
		"lat": "37.613697",
		"lon": "119.97793",
		"vsi": "960",
		"trak": "260",
		"sqk": "",
		"call": "",
		"gnd": "0",
		"trt": "2",
		"pos": "1",
		"mlat": "0",
		"tisb": "0",
		"mil": "0"
	}, {
		"postime": "1554216728881",
		"icao": "AB8862",
		"reg": "",
		"type": "",
		"spd": "380.7",
		"alt": "34000",
		"lat": "43.587698",
		"lon": "-59.114881",
		"vsi": "0",
		"trak": "257.7",
		"sqk": "0413",
		"call": "",
		"gnd": "0",
		"trt": "5",
		"pos": "1",
		"mlat": "0",
		"tisb": "0",
		"mil": "0"
	}, {
		"postime": "1554216728878",
		"icao": "400678",
		"reg": "",
		"type": "",
		"spd": "",
		"alt": "37975",
		"lat": "47.446198",
		"lon": "-64.811371",
		"vsi": "",
		"trak": "",
		"sqk": "",
		"call": "",
		"gnd": "0",
		"trt": "2",
		"pos": "1",
		"mlat": "0",
		"tisb": "0",
		"mil": "0"
	}, {
		"postime": "1554216728877",
		"icao": "780CDF",
		"reg": "",
		"type": "",
		"spd": "464",
		"alt": "36000",
		"lat": "-1.837921",
		"lon": "109.988972",
		"vsi": "0",
		"trak": "219.3",
		"sqk": "",
		"call": "",
		"gnd": "0",
		"trt": "2",
		"pos": "1",
		"mlat": "0",
		"tisb": "0",
		"mil": "0"
	}],
	"msg": "No error",
	"total": "9003",
	"ctime": "1554216731461"
}


[sample-result.json.zip](https://github.com/hazelcast/hazelcast-jet-demos/files/3034544/sample-result.json.zip)

**Comment by eminn** [comment]
Closing this since we've become a data feeder and changed the application to require an API key.
